{% set version = "1.7.1" %}

package:
    name: cdo
    version: {{ version }}

source:
    fn: cdo-{{ version }}.tar.gz
    url: https://code.zmaw.de/attachments/download/12070/cdo-{{ version }}.tar.gz
    md5: f513a4bef1cf081cab3cfdc79d177bc5

build:
    number: 2
    skip: True  # [win]

requirements:
    build:
        - jasper
        - libnetcdf 4.4.*
        - netcdf-fortran
        - proj.4
        - libuuid
    run:
        - jasper
        - libnetcdf 4.4.*
        - netcdf-fortran
        - proj.4
        - libgcc
        - libuuid

test:
    commands:
        - cdo -h
        - conda inspect linkages -n _test cdo  # [linux]

about:
    home: https://code.zmaw.de/projects/cdo
    license: GPLv2
    summary: CLI tools to manipulate and analyse Climate and NWP model Data

extra:
    recipe-maintainers:
        - ocefpaf
