{% set version = "2.1.0" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/27481/cdo-{{ version }}.tar.gz
  sha256: b871346c944b05566ab21893827c74616575deaad0b20eacb472b80b1fa528cc

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - gnuconfig  # [unix]
    - llvm-openmp  # [osx]
    - make  # [unix]
  host:
    - llvm-openmp  # [osx]
    - jasper
    - libcurl
    - libnetcdf
    - hdf5
    - proj
    - eccodes
    - libuuid
    - udunits2
    - libxml2
    - fftw
    - magics
  run:
    - llvm-openmp  # [osx]
    - jasper
    - libcurl
    - libnetcdf
    - hdf5
    - proj
    - eccodes
    - libuuid
    - udunits2
    - libxml2
    - fftw
    - magics

test:
  files:
    - dummy.nc
  commands:
    - cdo -V
    - cdo sinfo dummy.nc
    - cdo -graph,device=png,linewidth=1 -settaxis,2000-01-01,12:00:00,1days -expr,'t=sin(seq*3.141529/180.0)' -for,1,6000 t

about:
  home: https://code.zmaw.de/projects/cdo
  license: BSD-3-Clause
  license_file: COPYING
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data'

extra:
  recipe-maintainers:
    - zklaus
    - akrherz
    - Try2Code
    - ocefpaf
