{% set version = "1.9.8" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/20826/cdo-{{ version }}.tar.gz
  sha256: f2660ac6f8bf3fa071cf2a3a196b3ec75ad007deb3a782455e80f28680c5252a

build:
  number: 9
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
  host:
    - llvm-openmp  # [osx]
    - jasper
    - libnetcdf
    - hdf5
    - proj
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - ossuuid
  run:
    - llvm-openmp  # [osx]
    - jasper
    - libnetcdf
    - hdf5
    - proj
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - ossuuid

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  license_file: COPYING
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data'

extra:
  recipe-maintainers:
    - Try2Code
    - ocefpaf
