{% set version = "1.7.1" %}

package:
  name: cdo
  version: {{ version }}

source:
  fn: cdo-{{ version }}.tar.gz
  url: https://code.zmaw.de/attachments/download/12070/cdo-{{ version }}.tar.gz
  sha256: 5c24a5cb74dcf6e8b5140c67033868a5a0b641341e3adad3cb4035d5ad6e70a6

build:
  number: 6
  skip: True  # [win]

requirements:
  build:
    - jasper
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - util-linux  # [linux]
  run:
    - jasper
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - libgcc  # [linux]
    - util-linux  # [linux]

test:
  commands:
    - cdo -h
    #- conda inspect linkages -p $PREFIX cdo  # [not win]
    #- conda inspect objects -p $PREFIX cdo  # [osx]

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data.'

extra:
  recipe-maintainers:
    - ocefpaf
