{% set version = "1.7.1" %}

package:
    name: cdo
    version: {{ version }}

source:
    fn: cdo-{{ version }}.tar.gz
    url: https://code.zmaw.de/attachments/download/12070/cdo-{{ version }}.tar.gz
    md5: f513a4bef1cf081cab3cfdc79d177bc5

build:
    number: 4
    skip: True  # [win]

requirements:
    build:
        - jasper
        - libnetcdf 4.4.*
        - netcdf-fortran 4.4.*
        - proj.4 4.9.3
        - libuuid
    run:
        - jasper
        - libnetcdf 4.4.*
        - netcdf-fortran 4.4.*
        - proj.4 4.9.3
        - libgcc
        - libuuid

test:
    commands:
        - cdo -h
        #- conda inspect linkages -p $PREFIX cdo  # [not win]

about:
    home: https://code.zmaw.de/projects/cdo
    license: GPL-2.0
    summary: 'CLI tools to manipulate and analyse Climate and NWP model Data.'

extra:
    recipe-maintainers:
        - ocefpaf
