travis:
  secure:
    BINSTAR_TOKEN: RH0bHjDoCmoFcrrpnRmPJaGl8neGrekA63K4wuDQRee5La0kOm0u78Whx5Cs9j8lDI4s0Rzi/ghKZuTU/x/bpA67Cuas457uFHa7wQG9wmRl+UtSndTcPxL2MQswJuHg7kpL1x54OL8RfPzhq3XZaQ8Dtx9JhPrb1pQXPtsGR5p2HDj24YYQXmldfEEGxbvz5CmcpdQMDrFJVpEIdIKXDnjIFTctRXttCDSKkv4OibVJwrrUSSI28RKwen23r53QzXCUw47KgGfatKNwKO6DV2gsiVJkABFlz8fc78hHQh98Yy5y9tH4mDhaJ29mZjDDiwunzSBNb7VhxGSkEYz+p77e182OUh/5yxSMMMcCf1klJOqzdgcUe6vw5fP29HCKTmKmTUBsup4mhAGXU+SOnfT60reMUxCn7nFbax9xFFh173gWQAcSNP6kxlyq5SP1Chm8YUwt6GfLa6EwJ+X3wfttcCKGFdOLpM2x2RbGmptu97EeYzgsxb4oiydB7Jh3mXMtbbos0IoZ2/lTyDd91j5CEoEKekT/icLdj4k25D8Y4lskJ3DAEyOQzU8DJH1b2LjLI3pfiPZsHmCaOrbCEIxBDV/DDXyuSZYfl/Op2ObvZbZoshv8LnWztf1jBKVcW7n2fDzEa+oSwxD6re9Z0qsDN4QKiAG2FZQa28DHnMI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
